openapi: 3.0.3
info:
  title: Clockaburra Timesheet API
  version: 1.0.0
  description: API for managing timesheets, schedules, and employee data for Clockaburra Timesheet App.
servers:
  - url: http://localhost:8080
    description: Development server
  - url: https://clockaburra-restful-api.vercel.app/
    description: Production server
tags:
  - name: Users
    description: Operations related to users.
  - name: Authentication
    description: Operations related to authentication.
  - name: Clock
    description: Operation related to clock status of an user.
  - name: Shifts
    description: Operation related to the shifts of an user.
  - name: Timesheets
    description: Operation related to the timesheets of an user.
  - name: Roles
    description: Operation related to the possible roles for the users.
  - name: Departments
    description: Operation related to the possible departments for the users.
  - name: Images
    description: Operation related to images storage.
paths:
  /users:
    $ref: "./paths/users/users.yaml"
  /users/{id}:
    $ref: "./paths/users/usersById.yaml"
  /users/resend-validation-link/{id}:
    $ref: "./paths/users/resendLink.yaml"
  /users/reset-password:
    $ref: "./paths/users/reset-password.yaml"

  /auth/register:
    $ref: "./paths/auth/register.yaml"
  /auth/login:
    $ref: "./paths/auth/login.yaml"
  /auth/googleLogin:
    $ref: "./paths/auth/googleLogin.yaml"
  /auth/reset-password:
    $ref: "./paths/auth/resetPassword.yaml"
  /auth/me:
    $ref: "./paths/auth/me.yaml"
  /auth/validation:
    $ref: "./paths/auth/validation.yaml"

  /clock/{id}:
    $ref: "./paths/clock/getClock.yaml"
  /clock/in:
    $ref: "./paths/clock/in.yaml"
  /clock/out:
    $ref: "./paths/clock/out.yaml"
  /clock/breakStart:
    $ref: "./paths/clock/breakStart.yaml"
  /clock/breakEnd:
    $ref: "./paths/clock/breakEnd.yaml"

  /shift:
    $ref: "./paths/shift/shifts.yaml"
  /shift/{id}:
    $ref: "./paths/shift/shiftsById.yaml"

  /timesheet:
    $ref: "./paths/timesheet/timesheets.yaml"
  /timesheet/{id}:
    $ref: "./paths/timesheet/timesheetsById.yaml"
  /timesheet/approve:
    $ref: "./paths/timesheet/timesheetApprove.yaml"
  /timesheet/reject:
    $ref: "./paths/timesheet/timesheetReject.yaml"

  /role:
    $ref: "./paths/role/roles.yaml"
  /role/{id}:
    $ref: "./paths/role/rolesById.yaml"

  /department:
    $ref: "./paths/department/departments.yaml"
  /department/{id}:
    $ref: "./paths/department/departmentsById.yaml"

  /images/profile-images:
    $ref: "./paths/images/images.yaml"
  /images/profile-images/{filePath}:
    $ref: "./paths/images/deleteImage.yaml"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Users:
      $ref: "./components/schemas/users.yaml"
    NewUsers:
      $ref: "./components/schemas/newUsers.yaml"
    NewUsersResponse:
      $ref: "./components/schemas/newUsersResponse.yaml"
