openapi: 3.0.3
info:
  title: Clockaburra Timesheet API
  version: 1.0.0
  description: API for managing timesheets, schedules, and employee data for Clockaburra Timesheet App.
servers:
  - url: http://localhost:8080/
    description: Production server
tags:
  - name: Users
    description: Operations related to users.
  - name: Authentication
    description: Operations related to authentication.
  - name: Clock
    description: Operation related to clock status of an user.
  - name: shift
    description: Operation related to the shifts of an user.
  - name: timesheet
    description: Operation related to the timesheets of an user.
paths:
  /users:
    $ref: "http://localhost:8080/openapi/paths/users/users.yaml"
  /users/{id}:
    $ref: "http://localhost:8080/openapi/paths/users/usersById.yaml"
  /users/resend-validation-link/{id}:
    $ref: "http://localhost:8080/openapi/paths/users/resendLink.yaml"

  /auth/register:
    $ref: "http://localhost:8080/openapi/paths/auth/register.yaml"
  /auth/login:
    $ref: "http://localhost:8080/openapi/paths/auth/login.yaml"
  /auth/reset-password:
    $ref: "http://localhost:8080/openapi/paths/auth/resetPassword.yaml"
  /auth/me:
    $ref: "http://localhost:8080/openapi/paths/auth/me.yaml"
  /auth/validation:
    $ref: "http://localhost:8080/openapi/paths/auth/validation.yaml"

  /clock/{id}:
    $ref: "http://localhost:8080/openapi/paths/clock/getClock.yaml"
  /clock/in:
    $ref: "http://localhost:8080/openapi/paths/clock/in.yaml"
  /clock/out:
    $ref: "http://localhost:8080/openapi/paths/clock/out.yaml"
  /clock/breakStart:
    $ref: "http://localhost:8080/openapi/paths/clock/breakStart.yaml"
  /clock/breakEnd:
    $ref: "http://localhost:8080/openapi/paths/clock/breakEnd.yaml"

  /shift:
  /shift/{id}:
  /shift/user/{userId}:

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Users:
      $ref: "http://localhost:8080/openapi/components/schemas/users.yaml"
    NewUsers:
      $ref: "http://localhost:8080/openapi/components/schemas/newUsers.yaml"
    NewUsersResponse:
      $ref: "http://localhost:8080/openapi/components/schemas/newUsersResponse.yaml"
